require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/procedures', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Procedure. As you add validations to Procedure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Procedure.create! valid_attributes
      get procedures_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      procedure = Procedure.create! valid_attributes
      get procedure_url(procedure)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_procedure_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      procedure = Procedure.create! valid_attributes
      get edit_procedure_url(procedure)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Procedure' do
        expect do
          post procedures_url, params: { procedure: valid_attributes }
        end.to change(Procedure, :count).by(1)
      end

      it 'redirects to the created procedure' do
        post procedures_url, params: { procedure: valid_attributes }
        expect(response).to redirect_to(procedure_url(Procedure.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Procedure' do
        expect do
          post procedures_url, params: { procedure: invalid_attributes }
        end.to change(Procedure, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post procedures_url, params: { procedure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested procedure' do
        procedure = Procedure.create! valid_attributes
        patch procedure_url(procedure), params: { procedure: new_attributes }
        procedure.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the procedure' do
        procedure = Procedure.create! valid_attributes
        patch procedure_url(procedure), params: { procedure: new_attributes }
        procedure.reload
        expect(response).to redirect_to(procedure_url(procedure))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        procedure = Procedure.create! valid_attributes
        patch procedure_url(procedure), params: { procedure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested procedure' do
      procedure = Procedure.create! valid_attributes
      expect do
        delete procedure_url(procedure)
      end.to change(Procedure, :count).by(-1)
    end

    it 'redirects to the procedures list' do
      procedure = Procedure.create! valid_attributes
      delete procedure_url(procedure)
      expect(response).to redirect_to(procedures_url)
    end
  end
end
